"""
 constants ending with _VALUE or _FEE or _SURCHARGE are cents (euro)
 constants ending with _DISTANCE are meters

 Thinking about maintainability,
 a separate function could get and export these values.
"""
NO_SURCHARGE_MIN_CART_VALUE = 1000
FREE_DELIVERY_MIN_CART_VALUE = 20000

BASE_DELIVERY_DISTANCE = 1000
BASE_DELIVERY_FEE = 200
ADDITONAL_DISTANCE = 500
ADDITIONAL_DISTANCE_SURCHARGE = 100

BULK_ITEM_SURCHARGE = 120
BULK_ITEM_LIMIT = 12
BASE_ITEM_LIMIT = 4
ADDITIONAL_ITEM_SURCHARGE = 50

MAX_DELIVERY_FEE = 1500
RUSH_TIME_MULTIPLIER = 1.2

RUSH_DAY_OF_WEEK = 5
RUSH_HOUR_START = 15  # 3 PM UTC
RUSH_HOUR_END = 19  # 7 PM UTC
